# Uncomment this line to define a global platform for your project
platform :ios, '18.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.join(File.dirname(`which flutter`.strip), '..', 'packages', 'flutter_tools', 'bin', 'podhelper')

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end
