name: trale
description: trale - privacy-respecting body weight-diary

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.12.1+33

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dynamic_color: ^1.7.0
  file_picker: ^10.2.4
  file_saver: ^0.3.1
  fl_chart: ^1.0.0
  flutter_auto_size_text: ^4.1.0
  flutter_svg: ^2.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: ^0.19.0
  introduction_screen: ^3.1.17
  ml_linalg: ^13.12.6
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  phosphor_flutter: ^2.1.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  calendar_date_picker2: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.4

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  dependency_validator: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.9.2
  translations_cleaner: ^0.0.5

# define app icons
flutter_launcher_icons:
  image_path: "assets/launcher/icon.png"
  # image_path_ios: "assets/launcher/icon.png"
  # image_path_android: "assets/launcher/icon.png"
  ios: false
  android: true
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  adaptive_icon_monochrome: "assets/launcher/icon_monochrome.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # For internationalization
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/trale_icon_extended.svg
    - assets/trale_icon.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Black.ttf
          weight: 900
        - asset: fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-Light.ttf
          weight: 300
        - asset: fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: fonts/Lexend-Thin.ttf
          weight: 100
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
