name: trale
description: trale - privacy-respecting body weight-diary

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.1+24

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  dynamic_color: ^1.7.0
  file_picker: ^8.1.7
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  ml_linalg: ^13.12.6
  package_info_plus: ^8.1.3
  path_provider: ^2.1.5
  phosphor_flutter: ^2.1.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  calendar_date_picker2: ^1.1.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.4

dependency_overrides:
  intl: 0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  translations_cleaner: ^0.0.5


# define app icons
flutter_launcher_icons:
  image_path: "assets/launcher/icon.png"
  # image_path_ios: "assets/launcher/icon.png"
  # image_path_android: "assets/launcher/icon.png"
  ios: false
  android: true
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  adaptive_icon_monochrome: "assets/launcher/icon_monochrome.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # For internationalization
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/trale_icon_extended.svg
    - assets/trale_icon.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Black.ttf
          weight: 900
        - asset: fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-Light.ttf
          weight: 300
        - asset: fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: fonts/Lexend-Thin.ttf
          weight: 100
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
