name: quantumphysique
description: Shared Flutter library for QuantumPhysique apps — theme, preferences, notifier, widgets, settings pages, and changelog system.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dynamic_color: ^1.8.1
  flutter_auto_size_text: ^5.0.0
  flutter_local_notifications: ^21.0.0
  flutter_m3shapes_extended: ^1.1.0
  intl: ^0.20.2
  package_info_plus: ^9.0.1
  phosphor_flutter: ^2.1.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  timezone: ^0.11.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex-VariableFont_wght.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-VariableFont_wght.ttf
        - asset: fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic
