// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run quantumphysique:generate_changelog
// dart format off
// ignore_for_file: public_member_api_docs
// ignore_for_file: lines_longer_than_80_chars

part of 'changelog.dart';

/// The full parsed changelog from CHANGELOG.md.
const Changelog changelog = Changelog(<ChangelogEntry>[
  ChangelogEntry(
    version: 'Unreleased',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'All new interpolation: much faster with long histories, and more reliable across gaps. Your curve and rate of change may shift slightly',
        'New chart style "Scientific": your trend as a line, with the range in which your measurements are expected to fall',
        'The chart shows the part beyond your last measurement lighter, and dashed in "Scientific", as it is only a projection',
      ],
      ChangelogSection.otherChanges: <String>[
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.5.0',
    dateString: '2026-10-05',
    summary: 'Gingerbread has already returned to the shelves, but trale is ready: it can now\nhelp you maintain your weight through the holidays.',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'New goal "Maintain weight" to keep your weight steady (#454)',
        'A new target weight now starts at your current weight',
        'The interpolation preview of your own data now uses the zoom of the main chart (#512)',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the chart not updating right away after changing the unit',
        'Fixed saving an unchanged target weight restarting the "since goal" statistics',
        'Fixed the empty target weight field asking for a target date',
      ],
      ChangelogSection.otherChanges: <String>[
        'The chart no longer shades the gap between your weight and your target weight',
        'The area below the trend line in the chart has a new colour',
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.4.1',
    dateString: '2026-09-14',
    summary: 'That\'s one small step for mankind, one giant leap for trale: 200 stars on Github! Thx to all the great people supporting this app 🎉',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the reminder still firing when the weight was already logged that day',
        'Fixed dates showing a leading zero, e.g. "014/09", in French and Italian (#533)',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.4.0',
    dateString: '2026-09-09',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Tapping a reminder opens the add weight dialog right away',
        'The "system" colour palette now uses the full Material You palette of Android',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the launch screen always being white instead of following dark mode (#507)',
        'Fixed the Health Connect import reaching back only 30 days (#508)',
        'Fixed the Health Connect import not saying why nothing was imported (#508)',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved the wording of the translation banner and the reminder settings',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.3.1',
    dateString: '2026-08-31',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Use the latest Flutter (3.47) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the language selection showing "error" instead of العربية for Arabic (#515)',
        'Fixed the height field in the personalization settings losing focus after every digit (#509)',
        'Fixed the done key of the keyboard doing nothing in the height field',
        'Fixed the user dialog overlapping when the keyboard opens (#509)',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.3.0',
    dateString: '2026-08-26',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Reworked the measurement list: entries are now grouped by month and can be filtered by year and month (#460)',
        'Weight can now be typed on the keyboard: tap the value above the ruler in the add weight and target weight dialogs (#484)',
        'Added `-` and `+` buttons below the ruler to adjust the weight one step at a time',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the export writing microseconds in the timestamp of the latest measurement (#489)',
        'Fixed reminders firing at the wrong hour',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.2.0',
    dateString: '2026-07-01',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added Health Connect integration to synchronize weight measurements on Android (#475)',
        'Added quick action to add a new weight even faster (#468)',
      ],
      ChangelogSection.otherChanges: <String>[
        'New Material Expressive look for button groups',
        'Improved translation',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.1.0',
    dateString: '2026-06-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Përshëndetje botë! Thx to the community, the app is now available in Albanian 🎉',
        'Use the latest Flutter (3.44)',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.0.3',
    dateString: '2026-05-02',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the F-Droid release',
      ],
    },
  ),
  ChangelogEntry(
    version: '1.0.0',
    dateString: '2026-04-29',
    summary: 'Dear Tralers🐺,\ntrale v1.0 is out now, and we couldn\'t be more excited!🎉\nA huge thank you to every user, contributor, and translator: every commit, bug report, and idea mattered. A special shout-out to our Ko-fi sponsors: gh.com/lquenti, George, franciscoteca, ghStzyxh, Toasty2004, Peppin, Billy, and all anonymous donors. Knowing you\'re out there kept us motivated throughout the entire journey.\nWe can\'t wait to continue this journey with you.',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'A brand-new stats page with lots of new stats widgets',
        'Set a target date for your weight goal (#189)',
        'Reminder notifications for daily weight logging',
        'Major performance improvements throughout the app',
        '0.05 kg/st/lb entry steps for finer control',
        'Height can now be entered in imperial units (#326)',
        'Preview the interpolation on your own data',
        'Changelog now viewable in the app',
        'Tooltip shown while scrolling the chart',
        'Use the latest Flutter (3.41)',
      ],
      ChangelogSection.otherChanges: <String>[
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed importing OpenScale CSV files (#452, #455)',
        'Fixed the calendar with a custom first day of the week (#417, #418)',
        'Fixed a pop-up staying open after deleting measurements',
        'Fixed updating the target weight in the user dialog',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.15.1',
    dateString: '2026-02-03',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
        'Removed the white matte from the app icon',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.15.0',
    dateString: '2026-01-27',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'New app icon 🐺',
        'All new F-Droid store page with Material You Expressive (ready) Design 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved chart animation',
        'Improved translation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed negative time estimates when the weight does not change (#314)',
        'Fixed the backup reminder not going away (#394)',
        'Fixed the animation re-triggering when returning from settings to the overview tab (#402)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.14.0',
    dateString: '2026-01-06',
    summary: 'Welcome 2026! To help you shed those extra pounds gained over Christmas, we have completely revamped the app 🎆\nThis release is the foundation for the upcoming version 1.0. Now that the UI has been redesigned, we will focus again on new functionality in the next releases.',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Material You Expressive (ready) Design throughout the whole app 🎉',
        'Redesigned, more responsive weight picker',
        'Improved and all new Settings pages',
        'Use the latest Flutter (3.38) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'New font',
        'All new animations',
        'Removed the outdated onboarding screen',
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed selecting the zh-Hant variant',
        'Fixed missing hints on which imports are supported (#338, #357)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.13.2',
    dateString: '2025-09-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Added larger zoom levels for longtime users',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed several bugs of the zoom buttons (#333, #334)',
        'Fixed the scrollbar not being draggable',
        'Fixed misaligned measurements when using the am/pm format',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.13.1',
    dateString: '2025-09-10',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the F-Droid release (#342)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.13.0',
    dateString: '2025-09-07',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added zoom buttons, identical to double-tap',
        'Added iso8601 date format (#325)',
        'Target Android 16 (SDK 36)',
        'Use the latest Flutter (3.35) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed a typo in the about screen (#328)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.12.1',
    dateString: '2025-08-13',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the F-Droid release (#312)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.12.0',
    dateString: '2025-08-12',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        '3 brand new color themes',
        'Trale offers now 7 color scheme variants. Check out the settings page 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgraded deps',
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the BMI widget for st and lb (#301)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.11.2',
    dateString: '2025-07-15',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added a BMI widget (#239)',
        'Use the latest Flutter (3.32) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
        'Improved the change icon on the measurement screen (#263)',
        'Added a hint that the user\'s height is in centimeters',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.11.1',
    dateString: '2025-05-10',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Improved Material You design',
        'Use the latest Flutter (3.29.3) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.11.0',
    dateString: '2025-03-30',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'ஹலோ வேர்ல்ட்! Thx to the community, the app is now available in Tamil 🎉',
        'Use predictive back gesture',
        'The minimum target weight now follows your height (BMI) instead of a fixed value',
        'Added experimental high contrast mode',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the system color scheme for monochrome colors (#236)',
        'Fixed a wrong font color in some places',
        'Fixed the target label overlapping with the line',
        'Fixed reaching the goal being estimated as 0 days',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.10.1',
    dateString: '2025-03-03',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed a wrongly assigned button in the import screen',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.10.0',
    dateString: '2025-03-04',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Russian and Vietnamese 🎉',
        'Reworked import/export: Allowing now to save to files and import from openScale and Withings',
      ],
      ChangelogSection.otherChanges: <String>[
        'Minor speed improvements',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the unclear label of the gain weight mode',
        'Fixed the label of the Dutch language',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.3',
    dateString: '2025-02-25',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hallo wereld! Thx to the community, the app is now available in Dutch 🎉',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the shared file always being empty',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.2',
    dateString: '2025-02-15',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Здравей, свят! Thx to the community, the app is now available in Bulgarian 🎉',
        'Use the latest Flutter (3.29) with upgraded deps',
        'Added experimental mode to gain weight',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.1',
    dateString: '2025-01-31',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Target Android 15 (SDK 35)',
      ],
      ChangelogSection.otherChanges: <String>[
        'Design improvements',
        'Improved translation',
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the target weight showing in the interpolation preview',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.0',
    dateString: '2025-01-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Estonian and Slovenian 🎉',
        'Allow setting the first day of the week, thx to @olker159',
        'Use the latest Flutter (3.27) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved and restructured settings page',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the estimate of the current and max streak (#183)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.8.1',
    dateString: '2024-11-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the F-Droid release',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.8.0',
    dateString: '2024-11-10',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Extensively revised UI with lots of statistics to keep you engaged in achieving your dream weight 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Changed font and icons to improve overall accessibility',
        'Improved translation',
        'Added a backup reminder, see settings for more options',
        'Upgraded deps',
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed a small icon being shown in the F-Droid store (German)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.7.2',
    dateString: '2024-09-22',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Pozdrav svijete! Thx to the community, the app is now available in Croatian 🎉',
        'Use the latest Flutter (3.24) with upgraded deps',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed Ukrainian showing as a supported language',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.7.1',
    dateString: '2024-07-03',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Merhaba dünya! Thx to the community, the app is now available in Turkish 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgraded deps',
        'Improved readability of the target weight label',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the broken color of the line chart',
        'Fixed adding measurements older than 2 years',
        'Fixed the target weight shown in st/lb',
        'Fixed saving an unmodified measurement deleting it',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.7.0',
    dateString: '2024-05-29',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in French, Finnish, and Italian 🎉',
        'Use the latest Flutter (3.22) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.6.2',
    dateString: '2024-04-02',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the app not starting (#70)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.6.1',
    dateString: '2024-03-21',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'More reliable predictions',
        'Use the latest Flutter (3.19) with upgraded deps',
        'Target Android 14 (SDK 34)',
        'Hello World! Thx to the community, the app is now available in Lithuanian, Chinese, and Spanish 🎉',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed reloading the theme',
        'Fixed the interpolation not being shown with smoothing disabled (#25)',
      ],
      ChangelogSection.otherChanges: <String>[
        'Predictions with smoothing disabled now use a 2-day window',
        'Removed v0.6.0 due to critical bug when user target weight was set.',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.5.0',
    dateString: '2024-01-25',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Czech, Korean, Norwegian, and Polish 🎉',
        'Improved readme, screenshots, and app description',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.7',
    dateString: '2024-01-18',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Faster import',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed target weights below 50 kg being allowed',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.6',
    dateString: '2024-01-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed using lb and st units',
      ],
      ChangelogSection.otherChanges: <String>[
        'Fixed the F-Droid release',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.6',
    dateString: '2024-01-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed using lb and st units',
      ],
      ChangelogSection.otherChanges: <String>[
        'Fixed the F-Droid release',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.4',
    dateString: '2023-12-20',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fixed the app not loading without measurements',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgraded deps',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.3',
    dateString: '2023-11-26',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Use the latest Flutter (3.16) with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Removed the splash animation (#1)',
        'Fixed the list of used dependencies in the about screen',
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.2',
    dateString: '2023-11-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.1',
    dateString: '2023-10-30',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Upgraded deps',
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.0',
    dateString: '2023-10-25',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.apiChanges: <String>[
        'App id changed to `de.quantumphysique.trale`, upgrading is not possible!',
      ],
      ChangelogSection.addedFeatures: <String>[
        'Prepare F-Droid launch',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgraded deps',
        'Minor UI improvements',
        'Minor improvements to the code base',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the missing permission to open links',
        'Fixed overlapping monthly ticks in the chart, which now also show years',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.3.1',
    dateString: '2023-09-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added basic animation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the overview screen not updating after adding the first measurement',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.3.0',
    dateString: '2023-09-05',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added support for themed app icon (Android 13)',
        'Use the latest Flutter (3.13) with an improved Material You theme',
        'Updated measurement list',
        'Added import and export feature',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the broken theme selection',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.2.2',
    dateString: '2022-10-18',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'All new measurement screen including now achievements',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the start screen widget showing the 30 days average instead of the current slope',
      ],
      ChangelogSection.otherChanges: <String>[
        'More accurate history prediction',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.2.1',
    dateString: '2022-07-09',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added nice splash screen',
        'Adjust icon in drawer to theme and add slogan',
        'New and fresher app icon',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed date labels for ranges larger than 7 months',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved text on onboarding screen',
        'Added a German store description',
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.2.0',
    dateString: '2022-06-09',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Completely rewritten UI based on Material Design 3 and Flutter 3',
        'Improved prediction based on weighted linear regression',
        'Many new themes, improved zoom levels, many fixed bugs and so much more.',
      ],
      ChangelogSection.otherChanges: <String>[
        'Minor improvements to the code base',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.1.0',
    dateString: '2022-03-01',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'initial release',
      ],
    },
  ),
]);
