// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_changelog.dart
// ignore_for_file: public_member_api_docs
// ignore_for_file: lines_longer_than_80_chars

part of 'changelog.dart';

/// The full parsed changelog from CHANGELOG.md.
const Changelog changelog = Changelog(<ChangelogEntry>[
  ChangelogEntry(
    version: 'Unreleased',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Allows selecting 0.05kg/st/lb steps for more precision',
        'Major performance improvements by making app async',
        'Allow using imperial units for entering height',
        'Add reminder notifications to prompt daily weight logging',
        'Add option to preview interpolation on own data',
      ],
      ChangelogSection.otherChanges: <String>[
        'Using the latest flutter 3.41',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix broken calendar when choosing custom first Day of week option, #417 #418',
        'Fix persisting popup on deleting measurements',
        'Fix updating target weight in user dialog',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.15.1',
    dateString: '2026-02-03',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Improved translation',
        'Remove white matte in app icon',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.15.0',
    dateString: '2026-01-27',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'New app icon 🐺',
        'All new F-droid store page with Material You Expressive (ready) Design 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved chart animation',
        'Improved translation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix bug on negative time estimates when the slope is zero, #314',
        'Fix persisting Backup reminder, #394',
        'Fix Animation re-triggering when returning from settings to overview tab #402',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.14.0',
    dateString: '2026-01-06',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Material You Expressive (ready) Design throughout the whole app 🎉',
        'Redesigned, more responsive weight picker',
        'Improved and all new Settings pages',
      ],
      ChangelogSection.otherChanges: <String>[
        'Using the latest flutter 3.38',
        'New font family: RobotoFlex',
        'All new animations to align with M3E design guidelines',
        'Remove outdated onboarding screen',
        'Upgrade dependencies and building envs',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix bug which prevents selecting zh-Hant variant',
        'Add hints to explain which imports are supported, #338 and #357',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.13.2',
    dateString: '2025-09-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Added larger zoom levels for longtime users',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix several bugs of zoom buttons, #334 and #333',
        'Fix bug that scrollbar is not dragable',
        'Fix misaligned measurements when using am/pm format',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.13.1',
    dateString: '2025-09-10',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix Fdroid build, #342',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.13.0',
    dateString: '2025-09-07',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added zoom buttons, identical to double-tap',
        'Added iso8601 date format, #325',
      ],
      ChangelogSection.otherChanges: <String>[
        'Target Android 16 (SDK 36)',
        'Using the latest flutter 3.35 with upgraded deps',
        'Improved translation',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix typo in about screen, #328',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.12.1',
    dateString: '2025-08-13',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix Fdroid build, #312',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.12.0',
    dateString: '2025-08-12',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        '3 brand new color themes',
        'Trale offers now 7 color scheme variants. Check out the settings page 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgrade dependencies',
        'Upgrade building envs (Kotlin, Gradle, Android Application, and NDK)',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix `java heap space` error (CI) by increasing jvm memory',
        'Fix BMI widget for st and lbs, #301',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.11.2',
    dateString: '2025-07-15',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Thx to the community, many translations have been improved 🎉',
        'Using the latest flutter 3.32 with upgraded deps',
        'Add a BMI widget, #239',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improve change icon on measurement screen, #263',
        'Add a hint that the user\'s height is in centimeters',
      ],
      ChangelogSection.bugfix: <String>[
        'Replace `auto_size_text` dependency to support latest flutter version',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.11.1',
    dateString: '2025-05-10',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Thx to the community, many translations have been improved 🎉',
        'Improved material you design',
      ],
      ChangelogSection.otherChanges: <String>[
        'Using the latest flutter 3.29.3 with upgraded deps',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.11.0',
    dateString: '2025-03-30',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'ஹலோ வேர்ல்ட்! Thx to the community, the app is now available in Tamil 🎉',
        'Use predictive back gesture',
        'Incorporate user height to calculate BMI-based minimum target weight, replacing the predefined value.',
        'Added experimental high contrast mode',
      ],
      ChangelogSection.otherChanges: <String>[
        'Update translations',
        'Minor improvements',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix system color scheme for monochrome colors, #236',
        'Fix using wrong font color in some places',
        'Fix target label overlapping with line',
        'Fix returning achieving goal in 0 days',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.10.1',
    dateString: '2025-03-03',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix wrongly assign button action in import screen',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.10.0',
    dateString: '2025-03-04',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Russian and Vietnamese 🎉',
        'Reworked import/export: Allowing now to save to files and import from openScale and Withings',
      ],
      ChangelogSection.otherChanges: <String>[
        'Minor speed improvements',
      ],
      ChangelogSection.bugfix: <String>[
        'Make label of gain weight mode more clear',
        'Fix label for Dutch language',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.3',
    dateString: '2025-02-25',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Dutch 🎉',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixes a bug that caused the shared file to always be empty.',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.2',
    dateString: '2025-02-15',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Bulgarian 🎉',
        'Using the latest flutter 3.29 with upgraded deps',
        'Added experimental mode to gain weight',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.1',
    dateString: '2025-01-31',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Target SDK35 and use gradle 8.10',
        'Design improvements',
        'Thx to the community, added localizations for Italian, Estonian, and Chinese',
      ],
      ChangelogSection.bugfix: <String>[
        'Removed target weight from the interpolation preview',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.9.0',
    dateString: '2025-01-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Estonian and Slovenian 🎉',
        'Allow setting the first day of the week, thx to @olker159',
        'Using the latest flutter 3.27 with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved and restructured settings page',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed the estimation of the current/max streak, see #183',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.8.1',
    dateString: '2024-11-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Remove DependencyInfoBlock',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.8.0',
    dateString: '2024-11-10',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Extensively revised UI with lots of statistics to keep you engaged in achieving your dream weight 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Changed font and icons to improve overall accessibility',
        'Thx to the community, Spanish and French translation were improved',
        'Add backup reminder, see settings for more options',
        'Minor clean up of deprecated flutter code',
        'Upgraded deps',
      ],
      ChangelogSection.bugfix: <String>[
        'Fixed a bug that caused a small icon to be displayed in the F-Droid store (German).',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.7.2',
    dateString: '2024-09-22',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Croatian 🎉',
        'Using the latest flutter 3.24 with upgraded deps',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix showing ukraine as supported language',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.7.1',
    dateString: '2024-07-03',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Turkish 🎉',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgraded dependencies',
        'Improve readability of target weight label',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix broken color of linechart',
        'Allow adding measurements older than 2 years',
        'Fix bug of showing target weight correctly using st/lb',
        'Fixed a bug where saving an unmodified measurement resulted in it being deleted',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.7.0',
    dateString: '2024-05-29',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in French, Finnish, and Italian 🎉',
        'Using the latest flutter 3.22 with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improved translations',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.6.2',
    dateString: '2024-04-02',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix bug that prevents app to start, #70',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.6.1',
    dateString: '2024-03-21',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'All new and improved interpolation API, the predictions are now more reliable',
        'Using the latest flutter 3.19 with upgraded deps',
        'Compile against Android 14 (SDK34)',
        'Hello World! Thx to the community, the app is now available in Lithuanian, Chinese, and Spanish 🎉',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix bug, when reloading theme',
        'Fix bug that the interpolation was not shown for disabled smoothing, #25',
      ],
      ChangelogSection.otherChanges: <String>[
        'Disabling interpolation, will now use sigma=2days for extrapolation prediction',
        'Removed v0.6.0 due to critical bug when user target weight was set.',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.5.0',
    dateString: '2024-01-25',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Hello World! Thx to the community, the app is now available in Czech, Korean, Norwegian, and Polish 🎉',
        'Improved readme, screenshots, and app description (fastlane)',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.7',
    dateString: '2024-01-18',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Accelerated import',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix bug, that allowed target weights below 50 kg',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.6',
    dateString: '2024-01-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix bug, when using lb and st units',
      ],
      ChangelogSection.otherChanges: <String>[
        'Fix version error in 0.4.5',
        'Fix f-droid metadata',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.6',
    dateString: '2024-01-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix bug, when using lb and st units',
      ],
      ChangelogSection.otherChanges: <String>[
        'Fix version error in 0.4.5',
        'Fix f-droid metadata',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.4',
    dateString: '2023-12-20',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.bugfix: <String>[
        'Fix bug, which prevented loading the app without measurements',
      ],
      ChangelogSection.otherChanges: <String>[
        'Upgrade dependencies',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.3',
    dateString: '2023-11-26',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Using the latest flutter 3.16 with upgraded deps',
      ],
      ChangelogSection.otherChanges: <String>[
        'Prepare for predictive back gesture',
        'Removed splash animation to fix adding to f-droid, see #1',
        'Fixed list of used dependencies in about screen',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.2',
    dateString: '2023-11-14',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Remove build-id from rive to enable reproducible builds',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.1',
    dateString: '2023-10-30',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.otherChanges: <String>[
        'Upgrade dependencies',
        'Setup Proguard optimization',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.4.0',
    dateString: '2023-10-25',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.apiChanges: <String>[
        'App id changed to `de.quantumphysique.trale`, upgrading is not possible!',
      ],
      ChangelogSection.addedFeatures: <String>[
        'Prepare F-Droid launch',
      ],
      ChangelogSection.otherChanges: <String>[
        'Add github actions',
        'Upgrade dependencies',
        'Minor UI improvements',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix missing permission to open links',
        'Fixed overlapping monthly ticks and added years',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.3.1',
    dateString: '2023-09-08',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Add basic animation',
      ],
      ChangelogSection.bugfix: <String>[
        'Overview screen now updates upon adding first measurement',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.3.0',
    dateString: '2023-09-05',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Add support for themed app icon (android 13)',
        'Using the latest flutter 3.13 version with improved Material You theme',
        'Update measurement list',
        'Add import and export feature',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix broken theme selection',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.2.2',
    dateString: '2022-10-18',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'All new measurement screen including now achievements',
      ],
      ChangelogSection.bugfix: <String>[
        'Show current slope on start screen widget instead of 30 days average',
      ],
      ChangelogSection.otherChanges: <String>[
        'Added linear regression for history prediction',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.2.1',
    dateString: '2022-07-09',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Added nice splash screen',
        'Adjust icon in drawer to theme and add slogan',
        'New and fresher app icon',
      ],
      ChangelogSection.bugfix: <String>[
        'Fix showing date labels for ranges larger than 7 months',
      ],
      ChangelogSection.otherChanges: <String>[
        'Improve text on onboarding screen',
        'Add German meta data',
        'Remove unused files',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.2.0',
    dateString: '2022-06-09',
    sections: <ChangelogSection, List<String>>{
      ChangelogSection.addedFeatures: <String>[
        'Completely rewritten UI based on Material Design 3 and Flutter 3',
        'Improved prediction based on weighted linear regression',
        'Many new themes, improved zoom levels, many fixed bugs and so much more.',
      ],
      ChangelogSection.otherChanges: <String>[
        'Added fastlane to publish app',
      ],
    },
  ),
  ChangelogEntry(
    version: '0.1.0',
    dateString: '2022-03-01',
  ),
]);
