import 'dart:io';

import 'package:health/health.dart';
import 'package:quantumphysique/quantumphysique.dart';
import 'package:trale/core/measurement.dart';
import 'package:trale/core/measurement_database.dart';
import 'package:trale/core/preferences.dart';

/// Service that coordinates Google Health Connect reads and writes.
class HealthConnectService {
  /// Singleton constructor.
  factory HealthConnectService() => _instance;
  HealthConnectService._internal();
  static final HealthConnectService _instance =
      HealthConnectService._internal();

  final Health _health = Health();

  /// Whether the service has been initialized.
  bool _initialized = false;

  /// Track if a sync operation is in progress to prevent concurrent operations.
  bool _syncing = false;

  /// Initialize the service.
  Future<void> init() async {
    if (_initialized) {
      return;
    }
    await _health.configure();
    _initialized = true;
  }

  /// Check if Health Connect is available on the device.
  Future<bool> isAvailable() async {
    if (!Platform.isAndroid) {
      return false;
    }
    try {
      return await _health.isHealthConnectAvailable();
    } catch (e) {
      QPAppLogger.error(
        'Failed to check Health Connect availability',
        tag: 'HealthConnectService',
        error: e,
      );
      return false;
    }
  }

  /// Check if active read/write permissions for weight are granted.
  Future<bool> hasPermissions({required bool read, required bool write}) async {
    if (!Platform.isAndroid) {
      return false;
    }
    try {
      final List<HealthDataType> types = <HealthDataType>[
        HealthDataType.WEIGHT,
      ];
      final List<HealthDataAccess> permissions = <HealthDataAccess>[
        if (read && write)
          HealthDataAccess.READ_WRITE
        else if (read)
          HealthDataAccess.READ
        else if (write)
          HealthDataAccess.WRITE,
      ];
      final bool? has = await _health.hasPermissions(
        types,
        permissions: permissions,
      );
      return has ?? false;
    } catch (e) {
      QPAppLogger.error(
        'Failed to check Health Connect permissions',
        tag: 'HealthConnectService',
        error: e,
      );
      return false;
    }
  }

  /// Request read/write permissions for weight.
  Future<bool> requestPermissions({
    required bool read,
    required bool write,
  }) async {
    if (!Platform.isAndroid) {
      return false;
    }
    try {
      final List<HealthDataType> types = <HealthDataType>[
        HealthDataType.WEIGHT,
      ];
      final List<HealthDataAccess> permissions = <HealthDataAccess>[
        if (read && write)
          HealthDataAccess.READ_WRITE
        else if (read)
          HealthDataAccess.READ
        else if (write)
          HealthDataAccess.WRITE,
      ];
      return await _health.requestAuthorization(
        types,
        permissions: permissions,
      );
    } catch (e) {
      QPAppLogger.error(
        'Failed to request Health Connect permissions',
        tag: 'HealthConnectService',
        error: e,
      );
      return false;
    }
  }

  /// Revoke all Health Connect permissions.
  Future<void> revokePermissions() async {
    if (!Platform.isAndroid) {
      return;
    }
    try {
      await _health.revokePermissions();
    } catch (e) {
      QPAppLogger.error(
        'Failed to revoke Health Connect permissions',
        tag: 'HealthConnectService',
        error: e,
      );
    }
  }

  /// Import weight measurements from Health Connect.
  /// Discards records generated by Trale unless [ignoreOwnOrigin] is true.
  /// Prevents local duplicate entries.
  /// If [days] is null, fetches the full available history.
  Future<int> importMeasurements({
    int? days,
    bool ignoreOwnOrigin = false,
  }) async {
    if (_syncing) {
      return 0;
    }
    _syncing = true;
    try {
      return await _importMeasurements(
        days: days,
        ignoreOwnOrigin: ignoreOwnOrigin,
      );
    } finally {
      _syncing = false;
    }
  }

  Future<int> _importMeasurements({
    int? days,
    bool ignoreOwnOrigin = false,
  }) async {
    if (!Platform.isAndroid) {
      return 0;
    }
    try {
      final bool available = await isAvailable();
      if (!available) {
        return 0;
      }

      final bool hasRead = await hasPermissions(read: true, write: false);
      if (!hasRead) {
        QPAppLogger.warning(
          'No read permissions for Health Connect',
          tag: 'HealthConnectService',
        );
        return 0;
      }

      final DateTime now = DateTime.now();
      final DateTime startTime = days != null
          ? now.subtract(Duration(days: days))
          : DateTime.fromMillisecondsSinceEpoch(0);

      final List<HealthDataPoint> dataPoints = await _health
          .getHealthDataFromTypes(
            types: <HealthDataType>[HealthDataType.WEIGHT],
            startTime: startTime,
            endTime: now,
          );

      final List<Measurement> newMeasurements = <Measurement>[];
      for (final HealthDataPoint point in dataPoints) {
        // Discard entries where package origin is de.quantumphysique.trale
        // to prevent duplicate import of exported measurements.
        if (!ignoreOwnOrigin &&
            point.sourcePlatform == HealthPlatformType.googleHealthConnect &&
            (point.sourceId == 'de.quantumphysique.trale' ||
                point.sourceName == 'de.quantumphysique.trale')) {
          continue;
        }

        double? weightInKg;
        final dynamic val = point.value;
        if (val is NumericHealthValue) {
          weightInKg = val.numericValue.toDouble();
        } else if (val is num) {
          weightInKg = val.toDouble();
        } else if (val != null) {
          weightInKg = double.tryParse(val.toString());
        }

        if (weightInKg == null || weightInKg <= 0 || !weightInKg.isFinite) {
          continue;
        }

        final DateTime date = point.dateFrom;
        final Measurement m = Measurement(
          weight: weightInKg,
          date: date,
          isMeasured: true,
        );
        newMeasurements.add(m);
      }

      if (newMeasurements.isNotEmpty) {
        final int count = await MeasurementDatabase().insertMeasurementList(
          newMeasurements,
        );
        return count;
      }
      return 0;
    } catch (e) {
      QPAppLogger.error(
        'Failed to import measurements from Health Connect',
        tag: 'HealthConnectService',
        error: e,
      );
      return 0;
    }
  }

  /// Export a single measurement to Health Connect.
  Future<bool> exportMeasurement(Measurement m) async {
    if (!Platform.isAndroid) {
      return false;
    }
    try {
      final bool available = await isAvailable();
      if (!available) {
        return false;
      }

      final bool hasWrite = await hasPermissions(read: false, write: true);
      if (!hasWrite) {
        QPAppLogger.warning(
          'No write permissions for Health Connect',
          tag: 'HealthConnectService',
        );
        return false;
      }

      final DateTime date = m.date;
      return await _health.writeHealthData(
        value: m.weight,
        type: HealthDataType.WEIGHT,
        startTime: date,
        endTime: date,
      );
    } catch (e) {
      QPAppLogger.error(
        'Failed to export measurement to Health Connect',
        tag: 'HealthConnectService',
        error: e,
      );
      return false;
    }
  }

  /// Export all local Trale weight records to Health Connect.
  Future<int> exportAllMeasurements() async {
    if (_syncing) {
      return 0;
    }
    _syncing = true;
    try {
      return await _exportAllMeasurements();
    } finally {
      _syncing = false;
    }
  }

  Future<int> _exportAllMeasurements() async {
    if (!Platform.isAndroid) {
      return 0;
    }
    try {
      final bool available = await isAvailable();
      if (!available) {
        return 0;
      }

      final bool hasWrite = await hasPermissions(read: false, write: true);
      if (!hasWrite) {
        QPAppLogger.warning(
          'No write permissions for Health Connect',
          tag: 'HealthConnectService',
        );
        return 0;
      }

      final List<Measurement> all = MeasurementDatabase().measurements;
      int successCount = 0;
      for (final Measurement m in all) {
        final bool success = await exportMeasurement(m);
        if (success) {
          successCount++;
        }
      }
      return successCount;
    } catch (e) {
      QPAppLogger.error(
        'Failed to export all measurements to Health Connect',
        tag: 'HealthConnectService',
        error: e,
      );
      return 0;
    }
  }

  /// Perform a bidirectional sync of recent data (last 30 days).
  /// Imports external logs and exports local unsynced logs.
  Future<Map<String, int>> sync() async {
    if (_syncing) {
      return const <String, int>{'imported': 0, 'exported': 0};
    }
    _syncing = true;
    try {
      int imported = 0;
      int exported = 0;

      if (Preferences().healthConnectImportEnabled) {
        imported = await _importMeasurements(days: 30);
      }
      if (Preferences().healthConnectExportEnabled) {
        exported = await _exportAllMeasurements();
      }

      return <String, int>{'imported': imported, 'exported': exported};
    } finally {
      _syncing = false;
    }
  }
}
