/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
library;

import 'package:flutter/material.dart';

export 'package:quantumphysique/quantumphysique.dart' show PPIcon;

/// Class for custom icons
class CustomIcons {
  CustomIcons._();

  // font family name
  static const String _kFontFam = 'CustomIcons';

  /// Icon for medium interpolation strength.
  // ignore: constant_identifier_names
  static const IconData interpol_medium = IconData(
    0xe812,
    fontFamily: _kFontFam,
  );

  /// Icon for no interpolation.
  // ignore: constant_identifier_names
  static const IconData interpol_none = IconData(0xe813, fontFamily: _kFontFam);

  /// Icon for strong interpolation strength.
  // ignore: constant_identifier_names
  static const IconData interpol_strong = IconData(
    0xe814,
    fontFamily: _kFontFam,
  );

  /// Icon for weak interpolation strength.
  // ignore: constant_identifier_names
  static const IconData interpol_weak = IconData(0xe815, fontFamily: _kFontFam);
}
